// Code generated by ./gen/gen.go; DO NOT EDIT.
package color

var Cols = []Color{
	{
		ID:  0,
		Hex: "#000000",
	},
	{
		ID:  1,
		Hex: "#800000",
	},
	{
		ID:  2,
		Hex: "#008000",
	},
	{
		ID:  3,
		Hex: "#808000",
	},
	{
		ID:  4,
		Hex: "#000080",
	},
	{
		ID:  5,
		Hex: "#800080",
	},
	{
		ID:  6,
		Hex: "#008080",
	},
	{
		ID:  7,
		Hex: "#C0C0C0",
	},
	{
		ID:  8,
		Hex: "#808080",
	},
	{
		ID:  9,
		Hex: "#FF0000",
	},
	{
		ID:  10,
		Hex: "#00FF00",
	},
	{
		ID:  11,
		Hex: "#FFFF00",
	},
	{
		ID:  12,
		Hex: "#0000FF",
	},
	{
		ID:  13,
		Hex: "#FF00FF",
	},
	{
		ID:  14,
		Hex: "#00FFFF",
	},
	{
		ID:  15,
		Hex: "#FFFFFF",
	},
	{
		ID:  16,
		Hex: "#000000",
	},
	{
		ID:  17,
		Hex: "#00005F",
	},
	{
		ID:  18,
		Hex: "#000087",
	},
	{
		ID:  19,
		Hex: "#0000AF",
	},
	{
		ID:  20,
		Hex: "#0000D7",
	},
	{
		ID:  21,
		Hex: "#0000FF",
	},
	{
		ID:  22,
		Hex: "#005F00",
	},
	{
		ID:  23,
		Hex: "#005F5F",
	},
	{
		ID:  24,
		Hex: "#005F87",
	},
	{
		ID:  25,
		Hex: "#005FAF",
	},
	{
		ID:  26,
		Hex: "#005FD7",
	},
	{
		ID:  27,
		Hex: "#005FFF",
	},
	{
		ID:  28,
		Hex: "#008700",
	},
	{
		ID:  29,
		Hex: "#00875F",
	},
	{
		ID:  30,
		Hex: "#008787",
	},
	{
		ID:  31,
		Hex: "#0087AF",
	},
	{
		ID:  32,
		Hex: "#0087D7",
	},
	{
		ID:  33,
		Hex: "#0087FF",
	},
	{
		ID:  34,
		Hex: "#00AF00",
	},
	{
		ID:  35,
		Hex: "#00AF5F",
	},
	{
		ID:  36,
		Hex: "#00AF87",
	},
	{
		ID:  37,
		Hex: "#00AFAF",
	},
	{
		ID:  38,
		Hex: "#00AFD7",
	},
	{
		ID:  39,
		Hex: "#00AFFF",
	},
	{
		ID:  40,
		Hex: "#00D700",
	},
	{
		ID:  41,
		Hex: "#00D75F",
	},
	{
		ID:  42,
		Hex: "#00D787",
	},
	{
		ID:  43,
		Hex: "#00D7AF",
	},
	{
		ID:  44,
		Hex: "#00D7D7",
	},
	{
		ID:  45,
		Hex: "#00D7FF",
	},
	{
		ID:  46,
		Hex: "#00FF00",
	},
	{
		ID:  47,
		Hex: "#00FF5F",
	},
	{
		ID:  48,
		Hex: "#00FF87",
	},
	{
		ID:  49,
		Hex: "#00FFAF",
	},
	{
		ID:  50,
		Hex: "#00FFD7",
	},
	{
		ID:  51,
		Hex: "#00FFFF",
	},
	{
		ID:  52,
		Hex: "#5F0000",
	},
	{
		ID:  53,
		Hex: "#5F005F",
	},
	{
		ID:  54,
		Hex: "#5F0087",
	},
	{
		ID:  55,
		Hex: "#5F00AF",
	},
	{
		ID:  56,
		Hex: "#5F00D7",
	},
	{
		ID:  57,
		Hex: "#5F00FF",
	},
	{
		ID:  58,
		Hex: "#5F5F00",
	},
	{
		ID:  59,
		Hex: "#5F5F5F",
	},
	{
		ID:  60,
		Hex: "#5F5F87",
	},
	{
		ID:  61,
		Hex: "#5F5FAF",
	},
	{
		ID:  62,
		Hex: "#5F5FD7",
	},
	{
		ID:  63,
		Hex: "#5F5FFF",
	},
	{
		ID:  64,
		Hex: "#5F8700",
	},
	{
		ID:  65,
		Hex: "#5F875F",
	},
	{
		ID:  66,
		Hex: "#5F8787",
	},
	{
		ID:  67,
		Hex: "#5F87AF",
	},
	{
		ID:  68,
		Hex: "#5F87D7",
	},
	{
		ID:  69,
		Hex: "#5F87FF",
	},
	{
		ID:  70,
		Hex: "#5FAF00",
	},
	{
		ID:  71,
		Hex: "#5FAF5F",
	},
	{
		ID:  72,
		Hex: "#5FAF87",
	},
	{
		ID:  73,
		Hex: "#5FAFAF",
	},
	{
		ID:  74,
		Hex: "#5FAFD7",
	},
	{
		ID:  75,
		Hex: "#5FAFFF",
	},
	{
		ID:  76,
		Hex: "#5FD700",
	},
	{
		ID:  77,
		Hex: "#5FD75F",
	},
	{
		ID:  78,
		Hex: "#5FD787",
	},
	{
		ID:  79,
		Hex: "#5FD7AF",
	},
	{
		ID:  80,
		Hex: "#5FD7D7",
	},
	{
		ID:  81,
		Hex: "#5FD7FF",
	},
	{
		ID:  82,
		Hex: "#5FFF00",
	},
	{
		ID:  83,
		Hex: "#5FFF5F",
	},
	{
		ID:  84,
		Hex: "#5FFF87",
	},
	{
		ID:  85,
		Hex: "#5FFFAF",
	},
	{
		ID:  86,
		Hex: "#5FFFD7",
	},
	{
		ID:  87,
		Hex: "#5FFFFF",
	},
	{
		ID:  88,
		Hex: "#870000",
	},
	{
		ID:  89,
		Hex: "#87005F",
	},
	{
		ID:  90,
		Hex: "#870087",
	},
	{
		ID:  91,
		Hex: "#8700AF",
	},
	{
		ID:  92,
		Hex: "#8700D7",
	},
	{
		ID:  93,
		Hex: "#8700FF",
	},
	{
		ID:  94,
		Hex: "#875F00",
	},
	{
		ID:  95,
		Hex: "#875F5F",
	},
	{
		ID:  96,
		Hex: "#875F87",
	},
	{
		ID:  97,
		Hex: "#875FAF",
	},
	{
		ID:  98,
		Hex: "#875FD7",
	},
	{
		ID:  99,
		Hex: "#875FFF",
	},
	{
		ID:  100,
		Hex: "#878700",
	},
	{
		ID:  101,
		Hex: "#87875F",
	},
	{
		ID:  102,
		Hex: "#878787",
	},
	{
		ID:  103,
		Hex: "#8787AF",
	},
	{
		ID:  104,
		Hex: "#8787D7",
	},
	{
		ID:  105,
		Hex: "#8787FF",
	},
	{
		ID:  106,
		Hex: "#87AF00",
	},
	{
		ID:  107,
		Hex: "#87AF5F",
	},
	{
		ID:  108,
		Hex: "#87AF87",
	},
	{
		ID:  109,
		Hex: "#87AFAF",
	},
	{
		ID:  110,
		Hex: "#87AFD7",
	},
	{
		ID:  111,
		Hex: "#87AFFF",
	},
	{
		ID:  112,
		Hex: "#87D700",
	},
	{
		ID:  113,
		Hex: "#87D75F",
	},
	{
		ID:  114,
		Hex: "#87D787",
	},
	{
		ID:  115,
		Hex: "#87D7AF",
	},
	{
		ID:  116,
		Hex: "#87D7D7",
	},
	{
		ID:  117,
		Hex: "#87D7FF",
	},
	{
		ID:  118,
		Hex: "#87FF00",
	},
	{
		ID:  119,
		Hex: "#87FF5F",
	},
	{
		ID:  120,
		Hex: "#87FF87",
	},
	{
		ID:  121,
		Hex: "#87FFAF",
	},
	{
		ID:  122,
		Hex: "#87FFD7",
	},
	{
		ID:  123,
		Hex: "#87FFFF",
	},
	{
		ID:  124,
		Hex: "#AF0000",
	},
	{
		ID:  125,
		Hex: "#AF005F",
	},
	{
		ID:  126,
		Hex: "#AF0087",
	},
	{
		ID:  127,
		Hex: "#AF00AF",
	},
	{
		ID:  128,
		Hex: "#AF00D7",
	},
	{
		ID:  129,
		Hex: "#AF00FF",
	},
	{
		ID:  130,
		Hex: "#AF5F00",
	},
	{
		ID:  131,
		Hex: "#AF5F5F",
	},
	{
		ID:  132,
		Hex: "#AF5F87",
	},
	{
		ID:  133,
		Hex: "#AF5FAF",
	},
	{
		ID:  134,
		Hex: "#AF5FD7",
	},
	{
		ID:  135,
		Hex: "#AF5FFF",
	},
	{
		ID:  136,
		Hex: "#AF8700",
	},
	{
		ID:  137,
		Hex: "#AF875F",
	},
	{
		ID:  138,
		Hex: "#AF8787",
	},
	{
		ID:  139,
		Hex: "#AF87AF",
	},
	{
		ID:  140,
		Hex: "#AF87D7",
	},
	{
		ID:  141,
		Hex: "#AF87FF",
	},
	{
		ID:  142,
		Hex: "#AFAF00",
	},
	{
		ID:  143,
		Hex: "#AFAF5F",
	},
	{
		ID:  144,
		Hex: "#AFAF87",
	},
	{
		ID:  145,
		Hex: "#AFAFAF",
	},
	{
		ID:  146,
		Hex: "#AFAFD7",
	},
	{
		ID:  147,
		Hex: "#AFAFFF",
	},
	{
		ID:  148,
		Hex: "#AFD700",
	},
	{
		ID:  149,
		Hex: "#AFD75F",
	},
	{
		ID:  150,
		Hex: "#AFD787",
	},
	{
		ID:  151,
		Hex: "#AFD7AF",
	},
	{
		ID:  152,
		Hex: "#AFD7D7",
	},
	{
		ID:  153,
		Hex: "#AFD7FF",
	},
	{
		ID:  154,
		Hex: "#AFFF00",
	},
	{
		ID:  155,
		Hex: "#AFFF5F",
	},
	{
		ID:  156,
		Hex: "#AFFF87",
	},
	{
		ID:  157,
		Hex: "#AFFFAF",
	},
	{
		ID:  158,
		Hex: "#AFFFD7",
	},
	{
		ID:  159,
		Hex: "#AFFFFF",
	},
	{
		ID:  160,
		Hex: "#D70000",
	},
	{
		ID:  161,
		Hex: "#D7005F",
	},
	{
		ID:  162,
		Hex: "#D70087",
	},
	{
		ID:  163,
		Hex: "#D700AF",
	},
	{
		ID:  164,
		Hex: "#D700D7",
	},
	{
		ID:  165,
		Hex: "#D700FF",
	},
	{
		ID:  166,
		Hex: "#D75F00",
	},
	{
		ID:  167,
		Hex: "#D75F5F",
	},
	{
		ID:  168,
		Hex: "#D75F87",
	},
	{
		ID:  169,
		Hex: "#D75FAF",
	},
	{
		ID:  170,
		Hex: "#D75FD7",
	},
	{
		ID:  171,
		Hex: "#D75FFF",
	},
	{
		ID:  172,
		Hex: "#D78700",
	},
	{
		ID:  173,
		Hex: "#D7875F",
	},
	{
		ID:  174,
		Hex: "#D78787",
	},
	{
		ID:  175,
		Hex: "#D787AF",
	},
	{
		ID:  176,
		Hex: "#D787D7",
	},
	{
		ID:  177,
		Hex: "#D787FF",
	},
	{
		ID:  178,
		Hex: "#D7AF00",
	},
	{
		ID:  179,
		Hex: "#D7AF5F",
	},
	{
		ID:  180,
		Hex: "#D7AF87",
	},
	{
		ID:  181,
		Hex: "#D7AFAF",
	},
	{
		ID:  182,
		Hex: "#D7AFD7",
	},
	{
		ID:  183,
		Hex: "#D7AFFF",
	},
	{
		ID:  184,
		Hex: "#D7D700",
	},
	{
		ID:  185,
		Hex: "#D7D75F",
	},
	{
		ID:  186,
		Hex: "#D7D787",
	},
	{
		ID:  187,
		Hex: "#D7D7AF",
	},
	{
		ID:  188,
		Hex: "#D7D7D7",
	},
	{
		ID:  189,
		Hex: "#D7D7FF",
	},
	{
		ID:  190,
		Hex: "#D7FF00",
	},
	{
		ID:  191,
		Hex: "#D7FF5F",
	},
	{
		ID:  192,
		Hex: "#D7FF87",
	},
	{
		ID:  193,
		Hex: "#D7FFAF",
	},
	{
		ID:  194,
		Hex: "#D7FFD7",
	},
	{
		ID:  195,
		Hex: "#D7FFFF",
	},
	{
		ID:  196,
		Hex: "#FF0000",
	},
	{
		ID:  197,
		Hex: "#FF005F",
	},
	{
		ID:  198,
		Hex: "#FF0087",
	},
	{
		ID:  199,
		Hex: "#FF00AF",
	},
	{
		ID:  200,
		Hex: "#FF00D7",
	},
	{
		ID:  201,
		Hex: "#FF00FF",
	},
	{
		ID:  202,
		Hex: "#FF5F00",
	},
	{
		ID:  203,
		Hex: "#FF5F5F",
	},
	{
		ID:  204,
		Hex: "#FF5F87",
	},
	{
		ID:  205,
		Hex: "#FF5FAF",
	},
	{
		ID:  206,
		Hex: "#FF5FD7",
	},
	{
		ID:  207,
		Hex: "#FF5FFF",
	},
	{
		ID:  208,
		Hex: "#FF8700",
	},
	{
		ID:  209,
		Hex: "#FF875F",
	},
	{
		ID:  210,
		Hex: "#FF8787",
	},
	{
		ID:  211,
		Hex: "#FF87AF",
	},
	{
		ID:  212,
		Hex: "#FF87D7",
	},
	{
		ID:  213,
		Hex: "#FF87FF",
	},
	{
		ID:  214,
		Hex: "#FFAF00",
	},
	{
		ID:  215,
		Hex: "#FFAF5F",
	},
	{
		ID:  216,
		Hex: "#FFAF87",
	},
	{
		ID:  217,
		Hex: "#FFAFAF",
	},
	{
		ID:  218,
		Hex: "#FFAFD7",
	},
	{
		ID:  219,
		Hex: "#FFAFFF",
	},
	{
		ID:  220,
		Hex: "#FFD700",
	},
	{
		ID:  221,
		Hex: "#FFD75F",
	},
	{
		ID:  222,
		Hex: "#FFD787",
	},
	{
		ID:  223,
		Hex: "#FFD7AF",
	},
	{
		ID:  224,
		Hex: "#FFD7D7",
	},
	{
		ID:  225,
		Hex: "#FFD7FF",
	},
	{
		ID:  226,
		Hex: "#FFFF00",
	},
	{
		ID:  227,
		Hex: "#FFFF5F",
	},
	{
		ID:  228,
		Hex: "#FFFF87",
	},
	{
		ID:  229,
		Hex: "#FFFFAF",
	},
	{
		ID:  230,
		Hex: "#FFFFD7",
	},
	{
		ID:  231,
		Hex: "#FFFFFF",
	},
	{
		ID:  232,
		Hex: "#080808",
	},
	{
		ID:  233,
		Hex: "#121212",
	},
	{
		ID:  234,
		Hex: "#1C1C1C",
	},
	{
		ID:  235,
		Hex: "#262626",
	},
	{
		ID:  236,
		Hex: "#303030",
	},
	{
		ID:  237,
		Hex: "#3A3A3A",
	},
	{
		ID:  238,
		Hex: "#444444",
	},
	{
		ID:  239,
		Hex: "#4E4E4E",
	},
	{
		ID:  240,
		Hex: "#585858",
	},
	{
		ID:  241,
		Hex: "#626262",
	},
	{
		ID:  242,
		Hex: "#6C6C6C",
	},
	{
		ID:  243,
		Hex: "#767676",
	},
	{
		ID:  244,
		Hex: "#808080",
	},
	{
		ID:  245,
		Hex: "#8A8A8A",
	},
	{
		ID:  246,
		Hex: "#949494",
	},
	{
		ID:  247,
		Hex: "#9E9E9E",
	},
	{
		ID:  248,
		Hex: "#A8A8A8",
	},
	{
		ID:  249,
		Hex: "#B2B2B2",
	},
	{
		ID:  250,
		Hex: "#BCBCBC",
	},
	{
		ID:  251,
		Hex: "#C6C6C6",
	},
	{
		ID:  252,
		Hex: "#D0D0D0",
	},
	{
		ID:  253,
		Hex: "#DADADA",
	},
	{
		ID:  254,
		Hex: "#E4E4E4",
	},
	{
		ID:  255,
		Hex: "#EEEEEE",
	},
}
