#[derive(Debug, Clone)]
pub enum Msg {
    Quit,
    SwitchPane,

    ListPaneSelectNext,
    ListPaneSelectPrev,

    NotifyInfo(String),
    NotifyWarn(String),
    NotifyError(String),

    ToolPaneSelectUuidPage,
    ToolPaneSelectUlidPage,
    ToolPaneSelectHashPage,
    ToolPaneSelectUnixTimePage,
    ToolPaneSelectNumberBasePage,

    UuidPageSelectNextItem,
    UuidPageSelectPrevItem,
    UuidPageCurrentItemSelectNext,
    UuidPageCurrentItemSelectPrev,
    UuidPageScrollDown,
    UuidPageScrollUp,
    UuidPageGenerate,
    UuidPageCopy,
    UuidPagePaste,

    UlidPageSelectNextItem,
    UlidPageSelectPrevItem,
    UlidPageCurrentItemSelectNext,
    UlidPageCurrentItemSelectPrev,
    UlidPageScrollDown,
    UlidPageScrollUp,
    UlidPageGenerate,
    UlidPageCopy,
    UlidPagePaste,

    HashPageSelectNextItem,
    HashPageSelectPrevItem,
    HashPageCurrentItemSelectNext,
    HashPageCurrentItemSelectPrev,
    HashPageScrollDown,
    HashPageScrollUp,
    HashPageCopy,
    HashPagePaste,

    UnixTimePageSelectNextItem,
    UnixTimePageSelectPrevItem,
    UnixTimePageCurrentItemSelectNext,
    UnixTimePageCurrentItemSelectPrev,
    UnixTimePageEditStart,
    UnixTimePageEditEnd,
    UnixTimePageEditKeyEvent(ratatui::crossterm::event::KeyEvent),
    UnixTimePageCopy,
    UnixTimePagePaste,

    NumberBasePageSelectNextItem,
    NumberBasePageSelectPrevItem,
    NumberBasePageCurrentItemSelectNext,
    NumberBasePageCurrentItemSelectPrev,
    NumberBasePageEditStart,
    NumberBasePageEditEnd,
    NumberBasePageEditKeyEvent(ratatui::crossterm::event::KeyEvent),
    NumberBasePageCopy,
    NumberBasePagePaste,
}
